jenkinsci/instant-messaging-plugin

src/main/java/hudson/plugins/im/HudsonIsBusyListener.java
ScheduledExecutorService prevents graceful shutdown as it creates a user thread and prevents the JVM from shutting down. Can be reproduced with latest Tomcat 7.x.
=> instant-messaging-plugin prevents JVM from shutting down.

src/main/java/hudson/plugins/im/JenkinsIsBusyListener.java
Use existing NamingThreadFactory to name thread.
=> Use NamingThreadFactory + DaemonThreadFactory.

src/main/java/hudson/plugins/im/bot/BuildCommand.java
https://issues.jenkins-ci.org/browse/JENKINS-55757
=> [JENKINS-55757] BuildCommand.java : checkPermission() : report both nick and id for rejected sender

pom.xml
Common point of contention for many pending PRs
=> pom.xml : fix whitespace and bump required Jenkins core version

src/main/java/hudson/plugins/im/bot/QueueCommand.java
Builds upon refactoring from #33 and imports some of the benefits from #20
=> Queue cmd bot regex filtering

README.md, src/main/java/hudson/plugins/im/bot/CurrentlyBuildingCommand.java, src/main/java/hudson/plugins/im/bot/QueueCommand.java
Proceeds from #35 and #20 to document the usage of regex arguments in `currentlyBuilding` and `queue` bot commands.
=> Document regex bot args

pom.xml, src/main/java/hudson/plugins/im/IMConnectionProvider.java, src/main/java/hudson/plugins/im/IMPlugin.java, src/main/java/hudson/plugins/im/IMPublisher.java, src/main/java/hudson/plugins/im/IMPublisherDescriptor.java, src/main/java/hudson/plugins/im/NotificationStrategy.java, src/main/java/hudson/plugins/im/bot/CurrentlyBuildingCommand.java, src/main/java/hudson/plugins/im/bot/QueueCommand.java, src/main/java/hudson/plugins/im/build_notify/PrintFailingTestsBuildToChatNotifier.java
Aiming to have this plugin building again, not like it fails in PR #41 :)
Note that currently Jenkins artifactory does not resolve the findbugs-3.0.4 version, only 3.0.3 which seems to work for other plugins. So it might have been something about other parts of this pom.xml, e.g. lists of commands to run during a build/test...
=> Rearrange pom.xml like in ircbot-plugin, add jimklimov as maintainer

src/main/resources/hudson/plugins/im/IMPublisher/dropdownDescriptorSelector.jelly
Supposedly this factors into the table-to-div migration effort.
=> Forget tr+td around a hidden input

src/main/java/hudson/plugins/im/IMConnectionProvider.java
Do not silently swallow exceptions. Fixes JENKINS-62059.
=> Log IMException in IMConnectionProvider.create()

.mvn/extensions.xml, .mvn/maven.config, pom.xml, src/main/java/hudson/plugins/im/DefaultIMMessageTarget.java, src/main/java/hudson/plugins/im/GroupChatIMMessageTarget.java, src/main/java/hudson/plugins/im/IMMessageTarget.java, src/main/java/hudson/plugins/im/IMPublisherDescriptor.java, src/main/java/hudson/plugins/im/bot/UserStatCommand.java, src/main/java/hudson/plugins/im/tools/MessageHelper.java, src/test/java/hudson/plugins/im/MatrixNotificationTest.java, src/test/java/hudson/plugins/im/bot/BuildCommandTest.java, src/test/java/hudson/plugins/im/bot/HealthCommandTest.java
Requires https://github.com/jenkinsci/instant-messaging-plugin/pull/43
=> Add descriptor for Message targets

src/main/java/hudson/plugins/im/GroupChatIMMessageTarget.java
Tested with irc-bot plugin and all seems fine,
cc @jimklimov
=> Restore getPassword compatibility

.editorconfig, .github/CODEOWNERS, .github/dependabot.yml, .github/release-drafter.yml, .github/workflows/release-drafter.yml, pom.xml, src/main/java/hudson/plugins/im/bot/SnackCommand.java
Similar change to https://github.com/jenkinsci/ircbot-plugin/pull/39
=> Rearrange and update pom.xml following other plugins, and add github actions (dependabot et al)

README.md
=> README.md: update currentlyBuilding and queue command hints

pom.xml
See also https://github.com/jenkinsci/ircbot-plugin/pull/50 by @dependabot
=> pom.xml: bump maven-plugin to 3.13 and jenkins core to 2.289.1 with it

pom.xml, src/main/java/hudson/plugins/im/JenkinsIsBusyListener.java
Also update plugin via https://github.com/dependabot suggestion #118 which complained about this issue.
=> Fix spotbugs complaint

pom.xml
=> pom.xml: refer to variable scmTag

pom.xml, src/main/java/hudson/plugins/im/bot/Bot.java, src/main/java/hudson/plugins/im/bot/BuildCommand.java, src/main/java/hudson/plugins/im/bot/CurrentlyBuildingCommand.java, src/main/java/hudson/plugins/im/build_notify/PrintFailingTestsBuildToChatNotifier.java
Tags copied from lockable-resources plugin
TODO: SpotBugs did make suggestions - address them to merge :)
=> pom.xml: set spotbugs settings

pom.xml, src/main/java/hudson/plugins/im/IMPublisher.java, src/main/java/hudson/plugins/im/tools/BuildHelper.java, src/main/java/hudson/plugins/jabber/NotificationStrategy.java, src/test/java/hudson/plugins/im/IMPublisherTest.java
While that PR #171 might take some time to rectify, issues it uncovered might as well be fixed in main line.
=> Fix warnings exposed by PR #171

src/test/java/hudson/plugins/im/NotificationStrategyTest.java
```[tasklist]
```
In our analysis of the project, we observed that 
1)  1 unnecessary stubbing which stubbed `getPreviousBuild` method is created but never executed by one method call in the method `NotificationStrategyTest.testNewFailure`, which is invoked in 2 tests `NotificationStrategyTest.testAnyFailure`, `NotificationStrategyTest.testFailureAndFixed`;
2) 1 unnecessary stubbing which stubbed `getResult` method is created but never executed by one method call in the method `NotificationStrategyTest.testNewFailure`, which is invoked in the test `NotificationStrategyTest.testStateChangeOnly`;
Unnecessary stubbings are stubbed method calls that were never realized during test execution. Mockito recommends to remove unnecessary stubbings …
=> Removed 2 unnecessary stubbings in NotificationStrategyTest.java

src/test/java/hudson/plugins/im/tools/BuildHelperTest.java
```[tasklist]
```
In our analysis of the project, we observed that the test `BuildHelperTest.testIsFix` contains 2 unnecessary stubbings.
Unnecessary stubbings are stubbed method calls that were never realized during test execution. Mockito recommends to remove unnecessary stubbings (https://www.javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/exceptions/misusing/UnnecessaryStubbingException.html). 
We propose below a solution to remove the unnecessary stubbings.
=> Removed 2 unnecessary stubbings in BuildHelperTest.java

src/main/java/hudson/plugins/im/IMPublisher.java, src/main/java/hudson/plugins/im/bot/JobProvider.java
`mvn clean verify -DskipTests`
=> Stop using EOL JSR 305 annotations

src/main/java/hudson/plugins/im/AuthenticationHolder.java, src/main/java/hudson/plugins/im/IMConnectionProvider.java, src/main/java/hudson/plugins/im/bot/Bot.java, src/main/java/hudson/plugins/im/bot/BuildCommand.java
Migrate from deprecated functionality to non-deprecated equivalents.
=> Migrate from Acegi to Spring Security

src/test/java/hudson/plugins/im/IMPublisherTest.java, src/test/java/hudson/plugins/im/MatrixNotificationTest.java, src/test/java/hudson/plugins/im/NotificationStrategyTest.java, src/test/java/hudson/plugins/im/bot/AbstractMultipleJobCommandTest.java, src/test/java/hudson/plugins/im/bot/BuildCommandTest.java, src/test/java/hudson/plugins/im/bot/CommentCommandTest.java, src/test/java/hudson/plugins/im/bot/HealthCommandTest.java, src/test/java/hudson/plugins/im/bot/SnackCommandTest.java, src/test/java/hudson/plugins/im/tools/BuildHelperTest.java, src/test/java/hudson/plugins/im/tools/MessageHelperTest.java
This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.
=> Migrate tests to JUnit5
